SELECT * FROM project.emp;
SELECT ENAME, HIREDATE FROM EMP ORDER BY HIREDATE;

-- LIMIT INDEX, COUNT
SELECT ENAME, HIREDATE FROM EMP ORDER BY HIREDATE
LIMIT 0,3;
SELECT ENAME, HIREDATE FROM EMP ORDER BY HIREDATE
LIMIT 3,3;
SELECT ENAME, HIREDATE FROM EMP ORDER BY HIREDATE
LIMIT 6,8;
SELECT ENAME, HIREDATE FROM EMP ORDER BY HIREDATE
LIMIT 9,3;
SELECT ENAME, HIREDATE FROM EMP ORDER BY HIREDATE
LIMIT 12,3;