-- 2023.04.19

-- VIEW : 가상 테이블
-- VIEW 객체는 SQL를 가진다. => SQL실행결과를 가상의 테이블로 사용

SELECT EMPNO, ENAME,DEPTNO
FROM EMP
WHERE DEPTNO=30;

-- VIEW 객체 생성
-- CREATE OR REPLACE VIEW 뷰이름 AS 서브쿼리
CREATE OR REPLACE VIEW EMP_VIEW_30
AS
SELECT EMPNO, ENAME,DEPTNO
FROM EMP
WHERE DEPTNO=30;

SELECT * FROM EMP_VIEW_30;

-- 주문 정보 : ORDERS, BOOK, CUSTOMER 
SELECT O.ORDERID,C.NAME,B.BOOKNAME, B.PRICE, O.SALEPRICE, O.ORDERDATE
FROM ORDERS O, BOOK B, CUSTOMER C
WHERE O.BOOKID=B.BOOKID AND O.CUSTID=C.CUSTID;

-- VIEW 생성
CREATE OR REPLACE VIEW ORDER_INFO
AS
SELECT O.ORDERID,C.NAME,B.BOOKNAME, B.PRICE, O.SALEPRICE, O.ORDERDATE, C.PHONE
FROM ORDERS O, BOOK B, CUSTOMER C
WHERE O.BOOKID=B.BOOKID AND O.CUSTID=C.CUSTID;

-- VIEW 이용 가져오기
SELECT * FROM ORDER_INFO;
SELECT BOOKNAME, NAME FROM ORDER_INFO WHERE NAME='박지성';

-- 데이터 딕셔너리
SELECT VIEW_NAME, TEXT 
FROM USER_VIEWS; 
-- => 가지고 있는 뷰의 간략한 정보를 알려준다.

-- 뷰의 삭제
DROP VIEW EMP_VIEW_30;

SELECT ROWNUM ENAME, HIREDATE FROM EMP
ORDER BY HIREDATE;
-- => ROWNUM은 뷰에서 재정렬한다?

SELECT ROWNUM ENAME, HIREDATE
FROM (SELECT ROWNUM ENAME, HIREDATE FROM EMP
ORDER BY HIREDATE)
WHERE ROWNUM <=3
ORDER BY HIREDATE;
-- 특정 범위 여러개를 뽑을 떄 WHERE ROWNUM <=3

CREATE OR REPLACE VIEW EMP_HIREDATE_VIEW
AS
SELECT ENAME, HIREDATE FROM EMP
ORDER BY HIREDATE;

SELECT ROWNUM ENAME, HIREDATE FROM EMP_HIREDATE_VIEW
WHERE ROWNUM <=3;

SELECT TO_CHAR (HIREDATE, 'YYYY') FROM EMP;















