-- 2023/04/18
-- 오라클 외전

-- BULIT-IN FUNCTION => 오라클 내장 함수, 반드시 "하나"의 결과값이 존재한다

-- 테이블 1
CREATE TABLE ORACLE(
    BBASIC NUMBER (10) CONSTRAINT ORACLE_BBASIC_PK PRIMARY KEY ,
    ENAME VARCHAR(10),
    SHOOTING NUMBER (2),
    WLOC VARCHAR(10),
    HISTORY NUMBER(8) 
);

INSERT INTO ORACLE (BBASIC, ENAME, SHOOTING,WLOC,HISTORY)
VALUES(1,'SUAREZ',50,'바르셀',5);
INSERT INTO ORACLE (BBASIC, ENAME, SHOOTING,WLOC,HISTORY)
VALUES(2,'JERRAD',30,'리버풀',25);
INSERT INTO ORACLE (BBASIC, ENAME, SHOOTING,WLOC,HISTORY)
VALUES(3,'AGER',10,'바르셀',20);
INSERT INTO ORACLE (BBASIC, ENAME, SHOOTING,WLOC,HISTORY)
VALUES(4,'KLOPP',0,'DORTMOONT',10);
INSERT INTO ORACLE (BBASIC, ENAME, SHOOTING,WLOC,HISTORY)
VALUES (5,'COUTINEW',40,'바셀',5);

-- 테이블 2

CREATE TABLE RUNPLAYER (
    IINDEX NUMBER(10) CONSTRAINT RP_ID_FK REFERENCES ORACLE (BBASIC),
    RUNNAME VARCHAR (15) CONSTRAINT RP_RN_NN NOT NULL
);
INSERT INTO RUNPLAYER(IINDEX,RUNNAME)
VALUES (1,'수아레');
INSERT INTO RUNPLAYER(IINDEX,RUNNAME)
VALUES (5,'쿠통수');

SELECT * 
FROM ORACLE O, RUNPLAYER R
WHERE O.BBASIC=R.IINDEX;

















